### ISSUE TITLE
Thumbnail  doesn't work 

### ISSUE THREAD

**Issue by SpiritBaker** [SpiritBaker/Difficulty-and-AI#1]
No idea why and how to fix this. I've tried different formats png jpg different file size. It's just doesn't work.

**Comment by stackpoint** [comment]
This one: https://www.reddit.com/r/EU4mods/comments/hmebr0/how_do_i_upload_a_thumbnail_for_a_mod_on_the/

Or maybe these:
![image](https://user-images.githubusercontent.com/5704491/87484591-42a2f000-c5d2-11ea-87a8-09d8b9f50b27.png)
![image](https://user-images.githubusercontent.com/5704491/87484610-53536600-c5d2-11ea-98f0-1d5a6482113f.png)
![image](https://user-images.githubusercontent.com/5704491/87484640-6403dc00-c5d2-11ea-8ebf-f995493bf294.png)

**Comment by SpiritBaker** [comment]
yeah, the problem was it's just doesn't work locally. 

At least now I have thumbnail in steam. Thanks a lot.
