### ISSUE TITLE
Elections

### ISSUE THREAD

**Issue by stackpoint** [SpiritBaker/Difficulty-and-AI#6]
There are a couple ideas for election improvements that range in scope:

- [x] The AI reelection improvements Arumba made: https://github.com/TheDivexz/excelmakesbelhappypack/commit/2ffedbc38ffdba78f0204545b17a05bb04825621#diff-8113afe6cf29a03dc75648bd24aee15d
- [x] More likely to take stability hit for tradition: https://github.com/TheDivexz/excelmakesbelhappypack/commit/c7bd00f89f3cecd8cb748aacc3ffdd59bbdb099a#diff-0f974c5a7abb4a1597442c8d5ead611a
- [x] Minor variation in starting ruler stats: for example 0-2 minor skills, 3-5 major skill, chance to happen can be adjusted and ruler skills can be displayed in elections tooltip
- [x] Reelection-ruler length scaling tradition cost: https://github.com/TheDivexz/excelmakesbelhappypack/commit/d30adb3ffb13e632773bebff845834624ff0c6f2

**Comment by SpiritBaker** [comment]
I also had the impression that republics need semi random rulers, and if u are not abusing republic mechanic with short election cycles, u are playing it wrong etc.

**Comment by stackpoint** [comment]
I also remembered that there was also the ruler length tradition scaling I added in to nerf tradition gain: https://github.com/TheDivexz/excelmakesbelhappypack/commit/d30adb3ffb13e632773bebff845834624ff0c6f2

I'll work up a pull request if you're interested.

**Comment by SpiritBaker** [comment]
Let's add the whole thing, and look how the system works together
